### PR TITLE
setup basic map #24

### LINKED ISSUE #24: TASK-8: Setup basic map
As a developer, I need to have a basic map component to work on so that I can work on other user stories.

ACCEPTANCE CRITERIA
* Map is automatically in full screen
* Component would only have the map view and nothing else
* Must match [Mockup](https://www.figma.com/file/1XeyBVJ2XyC6AHDHYwxvdG/WayFinder-SOEN390?node-id=49%3A2)

### PR DESCRIPTION
**Pull request by bit172**
References #24 
* Added map that fits the whole screen
* Added screen navigation container component

### CODE REVIEW

**Comment by bit172** [comment]
Test isn't passing. Will need help with this one @TheGreatMarkus

**Review by osahtout — COMMENTED** [review]
What is that dummy file?

**Comment by bit172** [comment]
We needed them to commit since empty directories can't be added

**Comment by RGPosadas** [comment]
image
Jest test failing due to this file, you can maybe disable jest for this file until we're ready/we know what to test
@bit172 @JimLau49

**Comment by JimLau49** [comment]
image

I think we can do something like this to avoid it from checking this specific file

**Comment by JimLau49** [comment]
### **package.json**
image

Looked online and on the documentation for Jest and found that it should be something like this but its not passing.

image

**Review by RGPosadas — CHANGES_REQUESTED** [review]
Please change the travis line from:
`npm install -g expo-cli`
to
`npm install -g --loglevel=error expo-cli`
to declutter the build logs

**Review by JimLau49 — DISMISSED** [review]
LGTM

**Comment by RGPosadas** [comment]
Please also add the `--log-level=error` flag for any other npm installs
`WARN` level logs should be on the dev-side, not necessarily on the CI side

**Review by RGPosadas — CHANGES_REQUESTED** [review]
LGTM

**Review by RGPosadas — APPROVED** [review]

**Pull request merged**
