### PR TITLE
TASK-23: Upgrade Expo SDK

### PR DESCRIPTION
**Pull request by cristian-aldea**
This PR aims to upgrade all project dependencies to their highest compatible version, to be up to date with security patches and new features.

The supercheck was run and the unit tests were run and everything passed. A quick manual acceptance was also conducted to ensure that everything still worked, but the automated system tests will need to be run by either @RGPosadas , @osahtout or @cindyslittleplanet to make sure they still work.

Issue: #82

### CODE REVIEW

**Comment by bit172** [comment]
LGTM, but cannot approve since I can't run system tests.

**Review by RGPosadas — CHANGES_REQUESTED** [review]
Currently breaks the expo client being run on the iOS simulator
Will need to further debug on my end since only iOS users can run the simulator, so blocking it for now

**Comment by RGPosadas** [comment]
To help troubleshoot,

Detox works on RN <=0.61.*
Upgrading the expo SDK to 37.0.0 uses RN 0.61 internally (according to expo's [changelog](https://dev.to/expo/expo-sdk-37-is-now-available-69g)), so those may not be the reason why Detox isn't working

But still, will test after work is over to confirm that this isn't the issue

**Comment by cristian-aldea** [comment]
Just a note that my latest commit changes nothing in the content of the source code, it just modifies the files in accordance with prettier's new default configuration.

**Review by RGPosadas — APPROVED** [review]
#### Detox Tests
All tests pass.

#### Notes
Nice quality of life updates! LGTM 🚀

**Review by bit172 — APPROVED** [review]
Everything is still functional. LGTM

**Pull request merged**
