### PR TITLE
BUG-8: Travel routes cut through rooms in Hall 

### LINKED ISSUE #114: BUG-8: Travel routes cut through rooms in Hall
### Bug Description
Travel routes in the Hall building on the same floor cut through rooms for many start/end POI travel plans.

### Steps To Reproduce The Bug
1. Launch The application
2. Search for a start and a destination POI in the Hall building on the same floor
3. Start the travel plan

### What Is The Expected Result?
A travel route showing the shortest path is displayed.

### What Is The Actual Result?
A travel route is displayed but it cuts through rooms.

### Current Strategy
[x] Fix it now
[ ] Fix it later
[ ] Ignore it

### Additional Details/Screenshots
imageimageimageimage

### PR DESCRIPTION
**Pull request by bit172**
This PR fixes issue #114.

#### Screenshots:
imageimageimage

### CODE REVIEW

**Review by osahtout — DISMISSED** [review]
Tested on iPhone and LGTM. Someone with android should test before merging. 

IMG_601271DAE1B1-1


IMG_0093

**Review by ys-lin — DISMISSED** [review]
Tested with Android. LGTM.

image
image

**Review by leojrsilao — APPROVED** [review]
Tested it with iOS. LGTM :rocket: 
93382552_224683735467797_5339622111117836288_n

**Review by RGPosadas — APPROVED** [review]
Acceptance tests pass. LGTM!

**Review by r-saba — APPROVED** [review]
LGTM! Tested on android google pixel 2

**Pull request merged**
