### PR TITLE
Implemented basic highlights (Hall / Library) references #15

### LINKED ISSUE #15: US-2: Distinguish campus buildings
As a student, I want to be able to distinguish which buildings are part of the campus so that I will not confuse buildings.

### ACCEPTANCE CRITERIA
* Have overlays for all buildings in both SGW and Loyola campuses
* Must match [Mockup](https://www.figma.com/file/1XeyBVJ2XyC6AHDHYwxvdG/WayFinder-SOEN390?node-id=32%3A194)

### USER FLOW ACCEPTANCE
* All SGW buildings/annexes are present
* All Loyola building/annexes are present

### PR DESCRIPTION
**Pull request by leojrsilao**
This PR references issue #15

### CODE REVIEW

**Comment by RGPosadas** [comment]
Remember to follow our Git Rules guideline regarding PRs as well
https://github.com/RGPosadas/WayFinder/wiki/Git-Rules
image

**Comment by RGPosadas** [comment]
Build failing due to pre-commit check
Please install:
https://github.com/RGPosadas/WayFinder/wiki/Coding-Rules-and-Standards

**Comment by bit172** [comment]
Fellow teammate, may you please add the overlays as a separate component.

**Comment by leojrsilao** [comment]
> Fellow teammate, may you please add the overlays as a separate component.

Will do!

**Review by JimLau49 — APPROVED** [review]
LGTM

Taking back LGTM, acceptance criteria is not complete

**Review by JimLau49 — CHANGES_REQUESTED** [review]
Basic implementation is good, whats left is to finish the rest of the acceptance criteria (implement highlights for the rest of the buildings for the SGW campus and also loyola)

**Review by RGPosadas — DISMISSED** [review]
Functionality and mock-up wise, this is a LGTM!
Please note: annexes are part of buildings, so we have all of Concordia's buildings (which include annexes)

**Review by JimLau49 — APPROVED** [review]
Acceptance criteria was met

**Review by cristian-aldea — APPROVED** [review]
Looks good to me

**Pull request merged**
