### PR TITLE
HOTFIX: Separate POICategory.Escalator into EscalatorUp & EscalatorDown

### PR DESCRIPTION
**Pull request by osahtout**
This PR decouples Escalators category and connector to EscalatorUp & EscalatorDown to improve  pathfinding

### CODE REVIEW

**Review by cindyslittleplanet — DISMISSED** [review]
This is going to be really helpful in giving a more accurate path to the user, nice hotfix!

**Review by JimLau49 — DISMISSED** [review]
LGTM 🚀

**Review by leojrsilao — DISMISSED** [review]
LGTM!

**Review by RGPosadas — CHANGES_REQUESTED** [review]
Please modify your commit message to this format:
`HOTFIX: message content`

**Review by RGPosadas — APPROVED** [review]
LGTM

**Pull request merged**
