### PR TITLE
HOTFIX: Add stairs POI's on the 9th floor

### PR DESCRIPTION
**Pull request by ys-lin**
Added stairs 1, 2, 3 and fixed the location coordinates of stairs 4.

### CODE REVIEW

**Review by JimLau49 — DISMISSED** [review]
Looks good, thanks for including the additonal POIs

**Review by r-saba — DISMISSED** [review]
LGTM!

**Review by cindyslittleplanet — CHANGES_REQUESTED** [review]
Everything LGTM! Just rename your commit messages by `HOTFIX: message`.

**Review by cindyslittleplanet — APPROVED** [review]
Everything looks perfect now! Thank you :)

**Pull request merged**
