### PR TITLE
hotfix for POIs

### PR DESCRIPTION
**Pull request by ys-lin**
On H 9th floor:
- Fixed two POIs that were mapped to the same coordinate
- Fixed a POI that was mapped to the wrong coordinate
- Added 2 new POIs

On CC 1st floor:
- Fixed POIs with misplaced coordinates.

### CODE REVIEW

**Review by cristian-aldea — COMMENTED** [review]
Looks good, but if you could squash these commits before merging that would be great.

**Review by JimLau49 — APPROVED** [review]
LGTM

**Review by bit172 — APPROVED** [review]
LGTM

**Comment by leojrsilao** [comment]
LGTM! :clap:

**Pull request merged**
