### PR TITLE
TASK-6: Setup base project #20

### LINKED ISSUE #20: TASK-6: Setup base project
As a developer, I want to setup base project so that everyone can start working on the project on top of it.

AC:
* Push base project with expo
* Setup file structure
* Setup instructions written in README.md
* Setup libraries
   * react-native-nav
   * react-native-maps

### PR DESCRIPTION
**Pull request by cristian-aldea**
Fulfilled task acceptance criteria:
* Added expo-cli project
* Added setup instructions
* add react-native-maps dependency
* add react-native-nav dependency
* Update travis

### CODE REVIEW

**Review by RGPosadas — CHANGES_REQUESTED** [review]
Pls add issue number to all your commits on the first line
Even better, maybe squash some of your travis fixes into just one

**Comment by JimLau49** [comment]
just 1 thing , where are the 'Added setup instructions'

**Comment by cristian-aldea** [comment]
> just 1 thing , where are the 'Added setup instructions'

in README.md

**Comment by cristian-aldea** [comment]
> Pls add issue number to all your commits on the first line
> Even better, maybe squash some of your travis fixes into just one

please let me know of any other comments

**Review by JimLau49 — DISMISSED** [review]
LGTM

**Review by RGPosadas — DISMISSED** [review]
Let's Get This Moving 👍

**Comment by bit172** [comment]
LGTM!

**Review by bit172 — APPROVED** [review]

**Pull request merged**
