### PR TITLE
Set groundwork for TASK-14 and TASK-15

### PR DESCRIPTION
**Pull request by cristian-aldea**
This PR aims to set the common types and functions which will be used/implement for #45 and #46. 

The changes done include type definition, refactors and function definitions.

If you have questions, please feel free to leave them here.

### CODE REVIEW

**Review by RGPosadas — CHANGES_REQUESTED** [review]
Please start off your commit with `HOTFIX: <commit-message` for easier tracking

**Review by RGPosadas — APPROVED** [review]
I have no comments for the structure so LGTM

**Review by bit172 — APPROVED** [review]
LGTM

**Review by JimLau49 — APPROVED** [review]
Nice job looking foward to working on this story with u guys tmr 
LGTM 👍

**Review by leojrsilao — APPROVED** [review]
Structure LGTM! :metal:

**Review by ys-lin — APPROVED** [review]
LGTM

**Pull request merged**
